import { NextResponse, type NextRequest } from "next/server";

import { getServerClient } from "@/lib/auth/supabase";
import { env } from "@/lib/env";
import { logger } from "@/lib/logger";

/**
 * Auth callback — handles both supported sign-in flows from Supabase:
 *
 *   1. PKCE (`?code=...`)
 *      Used when the link was generated by an SSR client that stored a
 *      `code_verifier` cookie on /login (i.e. our normal `signInWithOtp`
 *      flow). We call `exchangeCodeForSession`.
 *
 *   2. Token-hash (`?token_hash=...&type=...`)
 *      Used by `admin.generateLink` (our `dev:magic-link` script) and the
 *      Supabase-recommended email-template pattern for Next.js App Router.
 *      No PKCE state required; the token hash itself is the verifier.
 *      We call `verifyOtp`.
 *
 *   3. Provider error (`?error=...&error_code=...`)
 *      Supabase couldn't verify the link — expired, already used, etc.
 *      We surface the real error on /login.
 *
 * What we DON'T support: the legacy "implicit flow" hash fragment
 * (`#access_token=...`). That format never reaches the server, so any
 * link that produces it is unusable here. If you see /login?error=missing_code
 * after clicking a link, the link came back in implicit form — regenerate
 * it via /login (PKCE) or via the dev:magic-link script (token_hash).
 */
export async function GET(request: NextRequest) {
  const url = new URL(request.url);
  const next = url.searchParams.get("next") || "/";

  const errorCode = url.searchParams.get("error_code");
  const errorParam = url.searchParams.get("error");
  if (errorCode || errorParam) {
    const description = url.searchParams.get("error_description");
    logger.warn(
      { error: errorParam, errorCode, description },
      "auth callback received provider error",
    );
    const target = new URL("/login", env.NEXT_PUBLIC_APP_URL);
    target.searchParams.set("error", errorCode ?? errorParam ?? "auth_error");
    if (description) target.searchParams.set("error_description", description);
    return NextResponse.redirect(target);
  }

  const tokenHash = url.searchParams.get("token_hash");
  const type = url.searchParams.get("type");
  const code = url.searchParams.get("code");

  if (!tokenHash && !code) {
    logger.warn(
      { search: url.search },
      "auth callback hit without code/token_hash (likely implicit-flow link)",
    );
    return NextResponse.redirect(
      new URL("/login?error=missing_code", env.NEXT_PUBLIC_APP_URL),
    );
  }

  try {
    const supabase = await getServerClient();

    if (tokenHash && type) {
      // Supabase's verifyOtp is a discriminated union: when `token_hash` is
      // present, `type` must be one of the EmailOtpType variants
      // ('magiclink' | 'recovery' | 'invite' | 'signup' | 'email_change' | 'email').
      // The SMS variant only accepts `phone` + `token`, never `token_hash`.
      type EmailOtpType =
        | "magiclink"
        | "recovery"
        | "invite"
        | "signup"
        | "email_change"
        | "email";
      const { error } = await supabase.auth.verifyOtp({
        type: type as EmailOtpType,
        token_hash: tokenHash,
      });
      if (error) {
        logger.warn(
          { code: error.code, status: error.status, message: error.message },
          "verifyOtp failed",
        );
        const target = new URL("/login", env.NEXT_PUBLIC_APP_URL);
        target.searchParams.set("error", error.code ?? "invalid_link");
        return NextResponse.redirect(target);
      }
      return NextResponse.redirect(new URL(next, env.NEXT_PUBLIC_APP_URL));
    }

    // PKCE path
    const { error } = await supabase.auth.exchangeCodeForSession(code!);
    if (error) {
      logger.warn(
        { code: error.code, status: error.status, message: error.message },
        "exchangeCodeForSession failed",
      );
      const target = new URL("/login", env.NEXT_PUBLIC_APP_URL);
      target.searchParams.set("error", error.code ?? "invalid_link");
      return NextResponse.redirect(target);
    }
    return NextResponse.redirect(new URL(next, env.NEXT_PUBLIC_APP_URL));
  } catch (err) {
    logger.error({ err }, "auth callback failed");
    return NextResponse.redirect(
      new URL("/login?error=callback_failed", env.NEXT_PUBLIC_APP_URL),
    );
  }
}
